### ISSUE TITLE
Error When Exiting ViewController that Includes Slider

### ISSUE THREAD

**Issue by e1399216** [jmenter/JAMAccurateSlider#1]
Hello,

I added your slider to an app. It seems to work good however when I exit the ViewController (pop) it displays the following exception message:

An instance 0x14db4680 of class UITableViewCellScrollView was deallocated while key value observers were still registered with it. Observation info was leaked, and may even become mistakenly attached to some other object. Set a breakpoint on NSKVODeallocateBreak to stop here in the debugger. Here's the current observation info:

<NSKeyValueObservationInfo 0x14dcaa40> (

<NSKeyValueObservance 0x14dcaa80: Observer: 0x14d9bb50, Key path: backgroundColor, Options: <New: NO, Old: YES, Prior: NO> Context: 0x113324, Property: 0x14dc0990>

)

2015-02-16 07:18:02.730 [296:60b] An instance 0x14d48a30 of class UITableViewCellScrollView was deallocated while key value observers were still registered with it. Observation info was leaked, and may even become mistakenly attached to some other object. Set a breakpoint on NSKVODeallocateBreak to stop here in the debugger. Here's the current observation info:

<NSKeyValueObservationInfo 0x14d32120> (

<NSKeyValueObservance 0x14d744f0: Observer: 0x14d48110, Key path: backgroundColor, Options: <New: NO, Old: YES, Prior: NO> Context: 0x113324, Property: 0x14dc0990>

)

**Comment by jmenter** [comment]
Thanks, I've been able to replicate this. I'll have a fix shortly.

**Comment by jmenter** [comment]
I've removed superview's backgroundColor KVO in release 1.1.1, which should fix this problem.

**Comment by e1399216** [comment]
Thanks Jmenter for your prompt reply and uislider control. Nice job.

**Comment by jmenter** [comment]
Thanks. What app have you added this slider to?
